# Generated by Django 5.2.4 on 2025-07-18 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Bilinmiyor', max_length=100)),
                ('tc_id', models.CharField(max_length=11, unique=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('city', models.CharField(default='-', max_length=50)),
                ('phone', models.CharField(default='-', max_length=20)),
                ('job', models.CharField(default='-', max_length=50)),
                ('referans', models.CharField(default='-', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(default='-', max_length=20)),
                ('license', models.CharField(default='-', max_length=50)),
                ('policy_type', models.CharField(default='-', max_length=50)),
                ('insurance_company', models.CharField(default='-', max_length=50)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='insurance_app.customer')),
            ],
        ),
    ]
